# Generated by Django 2.2 on 2019-05-12 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Workers',
            new_name='Worker',
        ),
    ]
