# Generated by Django 2.2 on 2019-05-12 20:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0002_auto_20190512_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='worker_tasks',
        ),
        migrations.AddField(
            model_name='worker',
            name='skillset',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='merge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeOfAllocation', models.DateTimeField()),
                ('taskToBePerformed', models.DateTimeField()),
                ('assetID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organize.Asset')),
                ('taskID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organize.Task')),
                ('workerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organize.Worker')),
            ],
        ),
    ]
