# Generated by Django 2.2 on 2019-05-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0003_auto_20190513_0155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='id',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='id',
        ),
        migrations.AlterField(
            model_name='asset',
            name='assetID',
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='taskID',
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='worker',
            name='workerID',
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
    ]
