# Generated by Django 2.2 on 2019-05-12 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0004_auto_20190513_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merge',
            name='taskToBePerformed',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='merge',
            name='timeOfAllocation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
