# Generated by Django 2.2 on 2019-05-12 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0006_auto_20190513_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merge',
            name='timeOfAllocation',
            field=models.DateField(),
        ),
    ]
