# Generated by Django 2.2 on 2019-05-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0007_auto_20190513_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merge',
            name='timeOfAllocation',
            field=models.DateTimeField(),
        ),
    ]
