# Generated by Django 2.2 on 2019-06-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0008_auto_20190513_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='assetID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='frequency',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='taskID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='worker',
            name='workerID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
